# Simulation
dt: 0.01 #time step of the simulation [s]
gravity: [0, 0, 0] # gravity [m/s2]

volume_file: "./data/skin_tissue.msh" #tetrahedral mesh (.msh) filename
rho: 40 # total mass 0.5*10^-4 kg
material: NeoHookean # constitutive law, choose among [StVenantKirchhoff, NeoHookean, Corotated]
E: 400 # Young's modulus 0.5*10^4 Pa
nu: 0.49 # Poisson ratio
